St 40 create component our catalog of products
MariiaSuper/shop_team_107 pull request #12
Opened 2024-10-01 10:52 UTC by MariiaSuper

2024-10-01 15:41 UTC, wasik07 requested changes
В загальному все добре внеси декілька змін
на рахунок роутерів, зроби так, щоб при натисканні на кнопку і якщо такої сторінки немає вікривався сторінка NotFoundPage

2024-10-01 15:41 UTC, wasik07 commented on src/components/Catalog/Catalog.tsx
> +          ml: '0px',
ml: '0px': Тут вказується нульове значення з одиницями пікселів. Це абсолютно допустимо, але зайве, оскільки значення нуль не потребує одиниць виміру.

ml: '0px', має бути ml: 0.

2024-10-01 15:41 UTC, wasik07 commented on src/components/Catalog/Catalog.tsx
> +          fontFamily: 'Roboto, sans-serif',
fontFamily: 'Roboto, sans-serif' тут  взагалі немає бути, якщо це стандартий  шфирт сторіки .
Також прибири fontFamily із інших частин коду.

2024-10-01 15:41 UTC, wasik07 commented on src/components/Catalog/Catalog.tsx
> +          lineHeight: '31.2px',
lineHeight: '31.2px', має бути у відносних одиницях виміру.
Також виправlineHeightі в інших частин коду.

2024-10-01 15:41 UTC, wasik07 commented on src/components/Catalog/Catalog.tsx
> +        Наш каталог товарів
рекомендація: можливо хай краще буде по центу?( я бачив як в фігма)

2024-10-01 15:41 UTC, wasik07 commented on src/components/Catalog/Catalog.tsx
> +    <Box sx={{ pt: 5, textAlign: 'center' }}>
![image](https://github.com/user-attachments/assets/7e099de4-2850-4f5a-a15c-ef8c6dfe83d8)
![image](https://github.com/user-attachments/assets/2f502b91-c9f3-4f81-8823-222e5ac9a45d)

Кнопки виходять за межі блоку а, також залазать в марджини, такого не має бути.

2024-10-01 15:41 UTC, wasik07 commented on src/components/Catalog/Catalog.tsx
> +              border: '1px solid #C6D7D7'
border: '1px solid #C6D7D7'
Додай колір в  createTheme і використовуй його звідти.
Також виправ#C6D7D7 в інших частин коду.

2024-10-01 15:41 UTC, wasik07 commented on src/components/Catalog/Catalog.tsx
> +              fontWeight: 590,
fontWeight: 590,

Значення 590 не є стандартним значенням, і більшість шрифтів не підтримують таке точне значення.

потрібно використовувати округлене до 100

Також виправ fontWeight: 590,  в інших частин коду.

2024-10-01 15:41 UTC, wasik07 commented on src/components/Catalog/Catalog.tsx
> +      <Box sx={{ mt: 2 }}>
<Box sx={{ mt: 2 }}> 
Верхні марджини можуть взаємодіяти з сусідніми елементами, що може призвести до неочікуваних результатів через злиття марджинів (margin collapsing). 
Верхі марджи не рекомендується використовувати 

Верхні марджини можна замінити на:

Нижні марджини (mb): замість margin-top використовувати margin-bottom для попереднього елемента.
Padding (pt, pb): додавати внутрішні відступи через padding-top або padding-bottom.
Flexbox або Grid: керувати простором між елементами за допомогою цих технологій (наприклад, використовуючи gap у Flexbox чи Grid).

2024-10-02 12:10 UTC, MariiaSuper commented on src/components/Catalog/Catalog.tsx
> +        Наш каталог товарів
I think that it is possible on a larger screen to grid this text in the center, and in this case - as per design

2024-10-02 14:34 UTC, wasik07 approved these changes

2024-10-02 14:49 UTC, merged